[environment]
cpu_count = 24
exec_env = "singularity"
free_mem = 74.4
overcommit_policy = "heuristic"
overcommit_limit = "50%"
nipype_version = "1.6.1"
templateflow_version = "0.7.1"
version = "20.2.3"

[execution]
bids_dir = "/work_dir/PredictEye/bids_data"
bids_database_dir = "/home/mszinte/projects/PredictEye/mri_analysis/work/20210827-080639_834c1a48-56d6-4a08-8b01-8d9f1fa0b95a/bids_db"
boilerplate_only = false
sloppy = false
debug = []
fmriprep_dir = "/work_dir/PredictEye/deriv_data/fmriprep_new/fmriprep"
fs_license_file = "/work_dir/freesurfer/license.txt"
fs_subjects_dir = "/work_dir/PredictEye/deriv_data/fmriprep_new/freesurfer"
layout = "BIDS Layout: .../work_dir/PredictEye/bids_data | Subjects: 20 | Sessions: 41 | Runs: 100"
log_dir = "/work_dir/PredictEye/deriv_data/fmriprep_new/fmriprep/logs"
log_level = 25
low_mem = true
md_only_boilerplate = false
notrack = false
output_dir = "/work_dir/PredictEye/deriv_data/fmriprep_new"
output_layout = "legacy"
output_spaces = "T1w"
reports_only = false
run_uuid = "20210827-080639_834c1a48-56d6-4a08-8b01-8d9f1fa0b95a"
participant_label = [ "01",]
templateflow_home = "/home/fmriprep/.cache/templateflow"
work_dir = "/home/mszinte/projects/PredictEye/mri_analysis/work"
write_graph = false

[workflow]
anat_only = false
aroma_err_on_warn = false
aroma_melodic_dim = -200
bold2t1w_dof = 12
bold2t1w_init = "register"
cifti_output = "170k"
fmap_bspline = false
force_syn = false
hires = true
ignore = [ "sbref",]
longitudinal = false
medial_surface_nan = false
regressors_all_comps = false
regressors_dvars_th = 1.5
regressors_fd_th = 0.5
run_reconall = true
skull_strip_fixed_seed = false
skull_strip_template = "OASIS30ANTs"
skull_strip_t1w = "force"
use_aroma = false
use_syn_sdc = false

[nipype]
crashfile_format = "txt"
get_linked_libs = false
memory_gb = 100.0
nprocs = 32
omp_nthreads = 8
plugin = "MultiProc"
resource_monitor = false
stop_on_first_crash = false

[seeds]
master = 12518
ants = 55569
numpy = 10430

[nipype.plugin_args]
maxtasksperchild = 1
raise_insufficient = false
